{
 "title": "Alpha",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Server CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"192.168.1.250:20200\"}"
    }
   ]
  },
  {
   "title": "JVM Thread Count",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{instance=\"192.168.1.250:20200\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "jvm_memory_allocated MB",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{instance=\"192.168.1.250:20200\"}/1024/1024",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "jvm_memory_used MB",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"192.168.1.250:20200\"}/1024/1024",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "GC Pause Seconds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_gc_pause_seconds_sum{instance=\"192.168.1.250:20200\"}",
     "legendFormat": "sum [{{cause}}]"
    },
    {
     "expr": "jvm_gc_pause_seconds_count{instance=\"192.168.1.250:20200\"}",
     "legendFormat": "count [{{cause}}]"
    },
    {
     "expr": "jvm_gc_pause_seconds_sum{instance=\"192.168.1.250:20200\"}/jvm_gc_pause_seconds_count{instance=\"192.168.1.250:20200\"}",
     "legendFormat": "sum/count [{{cause}}]"
    }
   ]
  }
 ]
}